### ISSUE TITLE
vendor script seems broken

### ISSUE THREAD

**Issue by ferd** [hexpm/hex_erl#19]
Not too sure if there's something off in how I'm using it (on linux):

```
λ hex_erl → master → ./vendor.sh
Usage: vendor.sh TARGET_DIR PREFIX
λ hex_erl → master → ./vendor.sh ../rebar3/src/ hex_
sed: -e expression #1, char 1: unknown command: `.'
λ hex_erl → master → ./vendor.sh ~/code/rebar3/src/ hex_
./vendor.sh: line 39: /home/ferd/code/rebar3/src//hex_hex_erl.hrl: No such file or directory
λ hex_erl → master → ./vendor.sh ~/code/rebar3/src hex_
./vendor.sh: line 39: /home/ferd/code/rebar3/src/hex_hex_erl.hrl: No such file or directory
```

I couldn't get it to do anything else but these things.

**Comment by wojtekmach** [comment]
should have used escript :)

**Comment by ericmj** [comment]
@ferd The script should be working of course but I am wondering if maybe rebar3 should use hex_erl as a dependency instead of vendoring. You already have other dependencies so I assume you don't have the issue with application conflicts or have solved it some other way?

**Comment by ferd** [comment]
@ericmj we can't use it as a dependency if we need it to fetch packages, because we need to bootstrap ourselves to eventually go fetch packages. We can't use the gpb plugin because we need a rebar3 to run that as well, and there are currently none in the system.

**Comment by ericmj** [comment]
Aha, that makes perfect sense. Thanks for the clarification.
